name: Manual Build
on:
  workflow_dispatch:

jobs:
  build-and-upload-artifacts:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写入权限来创建Release

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的提交历史用于版本检查

      - name: Modify mod version
        run: |
            MOD_VERSION="$(grep "mod_version" gradle.properties | cut -d '=' -f 2 | tr -d ' ')"
            COMMIT_MOD_VERSION="$(git describe --tags --exact-match 2>/dev/null | cut -d 'v' -f 2)"
            EVENT_NAME="${{ github.event_name }}" 
            
            if [[ "$MOD_VERSION" != "$COMMIT_MOD_VERSION" && "$EVENT_NAME" != "workflow_dispatch" ]]; then
              echo "::warning::Version mismatch！gradle.properties ($MOD_VERSION) vs tag ($COMMIT_MOD_VERSION)"
              echo "::warning::Mod version will be modified to $COMMIT_MOD_VERSION"
              sed -i "s/mod_version = $MOD_VERSION/mod_version = $COMMIT_MOD_VERSION/" gradle.properties
            fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vein_mine-${{ github.ref_name }}.jar
          path: build/libs/vein_mine-${{ github.ref_name }}.jar

